'use client'

import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode
} from 'react'

type Language = 'fr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

/* -------------------------------------------------------
   TRANSLATIONS
------------------------------------------------------- */
const translations: Record<Language, Record<string, string>> = {
  fr: {
    /* ---------------- HOME PAGE ---------------- */
    "siteTitle": "Coup de Pouce",
    "promoBannerTitle": "Inscription gratuite pour artisans et clients pendant 6 mois.",
    "promoBannerSubtitle": "Profitez de toutes les fonctionnalités sans frais pendant une période limitée.",
    "qualifiedArtisans": "Artisans qualifiés",
    "qualifiedArtisansDesc": "Des professionnels vérifiés et expérimentés à votre service",
    "artisans": "Artisans",
    "satisfiedClients": "Clients satisfaits",
    "satisfiedClientsDesc": "Des milliers de clients nous font confiance",
    "locationNotSpecified": "Lieu non spécifié",
    "noOffersAvailable": "Aucune offre disponible pour le moment",
    "welcomeText1": "Bienvenue sur Coup de Pouce, votre plateforme de mise en relation avec des artisans qualifiés.",
    "welcomeText2": "Trouvez rapidement le professionnel idéal pour tous vos travaux de rénovation, de réparation ou d'entretien.",
    "welcomeText3": "Nos artisans sont vérifiés, notés et prêts à répondre à vos besoins.",
    "heroTitle": "Coup de Pouce",
    "heroSubtitle": "Trouvez un artisan qualifié près de chez vous",
    "createAccount": "Créer un compte",
    "login": "Se connecter",
    "footerDescription": "La plateforme de confiance qui met en relation les clients avec des artisans qualifiés pour réaliser tous vos projets.",
    "quickLinks": "Liens rapides",
    "home": "Accueil",
    "about": "À propos",
    "about.title": "À propos de nous",
    "about.subtitle": "Votre partenaire de confiance pour tous vos travaux de rénovation",
    "about.mission": "Notre mission",
    "about.mission1": "Connecter les clients avec des artisans qualifiés et vérifiés",
    "about.mission2": "Faciliter la réalisation de projets de rénovation et de réparation",
    "about.commitment": "Nous nous engageons à offrir un service de qualité et une expérience utilisateur exceptionnelle",
    "about.projects": "Projets réalisés",
    "about.averageRating": "Note moyenne",
    "about.values": "Nos valeurs",
    "about.trust": "Confiance",
    "about.trustDesc": "Tous nos artisans sont vérifiés et notés",
    "about.efficiency": "Efficacité",
    "about.efficiencyDesc": "Trouvez rapidement l'artisan idéal pour vos projets",
    "about.proximity": "Proximité",
    "about.proximityDesc": "Des artisans disponibles près de chez vous",
    "about.howItWorks": "Comment ça marche",
    "about.signup": "S'inscrire",
    "about.signupDesc": "Créez votre compte client ou artisan",
    "about.publish": "Publier",
    "about.publishDesc": "Décrivez votre demande de travaux",
    "about.select": "Sélectionner",
    "about.selectDesc": "Choisissez parmi les propositions reçues",
    "about.realization": "Réalisation",
    "about.realizationDesc": "Réalisez vos projets avec les meilleurs artisans",
    "about.ctaTitle": "Prêt à commencer votre projet ?",
    "about.ctaSubtitle": "Rejoignez des milliers de clients satisfaits",
    "about.signUp": "S'inscrire",
    "about.contactUs": "Nous contacter",
    "about.backHome": "Retour à l'accueil",
    "signup": "S'inscrire",
    "services": "Services",
    "clientSpace": "Espace client",
    "artisanSpace": "Espace artisan",
    "legal": "Légal",
    "terms": "Conditions générales",
    "privacy": "Politique de confidentialité",
    "artisanTerms": "Conditions artisans",
    "contactLink": "Contact",
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Notre équipe est là pour vous aider et répondre à toutes vos questions",
    "contact.info": "Informations de contact",
    "contact.email": "Email",
    "contact.emailValue": "contact@coupdepouce.fr",
    "contact.form": "Formulaire de contact",
    "contact.name": "Nom",
    "contact.emailLabel": "Email",
    "contact.subject": "Sujet",
    "contact.message": "Message",
    "contact.userType": "Type d'utilisateur",
    "contact.client": "Client",
    "contact.company": "Entreprise",
    "contact.send": "Envoyer",
    "contact.successTitle": "Message envoyé avec succès !",
    "contact.successMessage": "Nous vous répondrons dans les plus brefs délais.",
    "contact.backHome": "Retour à l'accueil",
    "copyright": "© 2026 Coup de Pouce. Tous droits réservés.",
    "support": "Support",
    "welcome": "Bienvenue",
    "error": "Erreur",
    /* ---------------- CLIENT DASHBOARD ---------------- */
    "clientDashboard.title": "Tableau de bord client",
    "dashboard.logout": "Déconnexion",
    "clientDashboard.myDemands": "Mes demandes",
    "clientDashboard.createDemand": "Créer une demande",
    "clientDashboard.proposals": "Propositions",
    "clientDashboard.messages": "Messages",
    "clientDashboard.editProfile": "Modifier le profil",
    "clientDashboard.noProposals": "Aucune proposition reçue.",
    "clientDashboard.contactArtisan": "Contacter",
    "clientDashboard.phone": "Téléphone",
    "clientDashboard.loading": "Chargement…",
    "clientDashboard.backToDashboard": "Retour au tableau de bord",
    "clientDashboard.unknownArtisan": "Artisan inconnu",
    "clientDashboard.unspecifiedTrade": "Métier non spécifié",
    "clientDashboard.delete": "Supprimer",
    "clientDashboard.confirmDelete": "Êtes-vous sûr de vouloir supprimer cette proposition ?",
    "clientDashboard.confirmDeleteDemand": "Êtes-vous sûr de vouloir supprimer cette demande ?",
    "clientDashboard.noDemands": "Aucune demande trouvée.",
    "clientDashboard.status": "Statut",
    "clientDashboard.createdOn": "Créé le",
    "clientDashboard.viewProposals": "Voir les propositions",
    "clientDashboard.client": "Client",
    "clientDashboard.contactClient": "Contacter le client",
    "clientDashboard.messageCount": "Nombre de messages",
    "clientDashboard.openConversation": "Ouvrir la conversation",
    "clientDashboard.confirmDeleteMessage": "Êtes-vous sûr de vouloir supprimer cette conversation ?",
    "artisanDashboard.myProposals": "Mes propositions",
    "artisanDashboard.noProposals": "Aucune proposition envoyée.",
    "artisanDashboard.myMessages": "Mes messages",
    "artisanDashboard.noMessages": "Aucune conversation trouvée.",
    "location": "Lieu",
    "unsubscribe.title": "Se désinscrire",
    "unsubscribe.confirm": "Êtes-vous sûr de vouloir vous désinscrire ?",
    /* ---------------- CREATE DEMAND ---------------- */
    "createDemand.title": "Créer une demande",
    "form.title": "Titre",
    "form.description": "Description",
    "form.city": "Ville",
    "form.department": "Département",
    "form.category": "Catégorie",
    "form.budget": "Budget estimé",
    "form.createDemand": "Créer la demande",
    "form.categoryPlaceholder": "Ex: Plomberie, Électricité, Menuiserie",
    "form.budgetPlaceholder": "Ex: 500-1000€",
    "form.notAuthenticated": "Non authentifié",
    "form.back": "Retour",
    /* ---------------- PROFILE EDIT ---------------- */
    "profileEdit.title": "Modifier mon profil",
    "profileEdit.loading": "Chargement du profil...",
    "profileEdit.return": "Retour",
    "profileEdit.uploadPhoto": "Uploader une photo de profil",
    "profileEdit.deletePhoto": "Supprimer la photo",
    "profileEdit.fullName": "Nom complet",
    "profileEdit.email": "Email",
    "profileEdit.phone": "Téléphone",
    "profileEdit.city": "Ville",
    "profileEdit.firstName": "Prénom",
    "profileEdit.lastName": "Nom",
    "profileEdit.trade": "Métier",
    "profileEdit.selectTrade": "Sélectionnez un métier",
    "profileEdit.description": "Description",
    "profileEdit.experienceYears": "Années d'expérience",
    "profileEdit.specialties": "Spécialités",
    "profileEdit.saving": "Enregistrement...",
    "profileEdit.saveChanges": "Enregistrer les modifications",
    "profileEdit.profileNotFound": "Profil introuvable",
    "profileEdit.unableToSave": "Impossible d'enregistrer les modifications",
    "profileEdit.updatedSuccessfully": "Profil mis à jour avec succès",
    /* ---------------- PROPOSALS ---------------- */
    "proposals.title": "Envoyer une proposition",
    "proposals.respondingTo": "Vous répondez à la demande :",
    "proposals.messageLabel": "Message à envoyer au client",
    "proposals.messagePlaceholder": "Expliquez comment vous pouvez aider, vos disponibilités, etc.",
    "proposals.cancel": "Annuler",
    "proposals.sending": "Envoi en cours...",
    "proposals.send": "Envoyer la proposition",
    "proposals.loading": "Chargement...",
    "proposals.demandNotFound": "Demande introuvable",
    "proposals.back": "Retour",
    /* ---------------- MESSAGES ---------------- */
    "messages.conversation": "Conversation",
    "messages.typeMessage": "Tapez votre message...",
    "messages.send": "Envoyer",
    "messages.downloadFile": "Télécharger le fichier",
    "no_conversations": "Aucune conversation",
    "clickToReply": "Cliquez pour répondre",
    /* ---------------- HOME SLIDESHOW ---------------- */
    "slideshow.title": "Dernières demandes",
    "slideshow.noProposals": "Aucune proposition disponible",
    /* ---------------- ARTISAN DASHBOARD ---------------- */
    "artisanHeader": "Tableau de bord artisan",
    "logout": "Se déconnecter",
    "proposals": "Propositions",
    "messages": "Messages",
    "editProfile": "Modifier le profil",
    "unsubscribe": "Se désinscrire",
    "unsubscribeConfirm": "Êtes-vous sûr de vouloir vous désinscrire ?",
 /* ---------------- ARTISAN PROFILE ---------------- */
"artisanProfile": "Mon profil artisan",
"backToDashboard": "Retour au tableau de bord",
"loading": "Chargement...",
"profileUpdated": "Profil mis à jour avec succès",
"errorLoadingProfile": "Erreur lors du chargement du profil",
"errorUpdatingProfile": "Erreur lors de la mise à jour du profil",
"connectionError": "Erreur de connexion",
"artisanProfileTitle": "Mon profil artisan",

"fullName": "Nom complet",
"email": "Email",
"phone": "Téléphone",
"city": "Ville",
"trade": "Métier / Profession",
"experienceYears": "Années d'expérience",

"description": "Description",
"descriptionPlaceholder": "Décrivez vos services et votre expertise...",

"specialties": "Spécialités",
"specialtiesPlaceholder": "Ex: Plomberie, Chauffage, Salle de bain",

"saveChanges": "Enregistrer les modifications",
"saving": "Enregistrement...",

    /* ---------------- ARTISAN DASHBOARD INSCRIPTION INFO ---------------- */
    "myArtisanProfile": "Profil Artisan",
    "description Section": "Description",
    "description Placeholder2": "Décrivez votre activité...",
    "experience Years": "Années d'expérience",
    "specialties Section": "Spécialités",
    "specialties Placeholder2": "Ex: Maçonnerie, Rénovation...",
    "contact": "Contact",
    "phonePlaceholder": "Téléphone",
    "cityPlaceholder": "Ville",
    "cancel": "Annuler",
    "save": "Enregistrer",
    "updateError": "Erreur lors de la mise à jour",
    /* ---------------- ARTISAN CONTACTS ---------------- */
    "welcomeContacts": "Bienvenue, {name} - Mes contacts",
    "manageContacts": "Gérez vos communications avec les clients",
    "loadingContacts": "Chargement des contacts...",
    "noContacts": "Aucun contact",
    "noContactsDesc": "Vous n'avez pas encore de contacts avec des clients.",
    "viewRequests": "Consulter les demandes disponibles",
    "deleteContact": "Supprimer",
    "deleteContactConfirm": "Êtes-vous sûr de vouloir supprimer ce contact ?",
    "contactDetails": "Détails du contact",
    "clientInfo": "Informations client",
    "name": "Nom",
    "status": "Statut",
    "address": "Adresse",
    "demandInfo": "Informations sur la demande",
    "title": "Titre",
    "category": "Catégorie",
    "contactDate": "Date du contact",
    "proposedPrice": "Prix proposé",
    "communication": "Communication",
    "client": "Client",
    "yourResponse": "Votre réponse",
    "responseSent": "Réponse envoyée",
    "close": "Fermer",
    "contactClient": "Contacter le client",
    "statusInitial": "Initial",
    "statusOngoing": "En cours",
    "statusCompleted": "Terminé",
    "statusUnknown": "Inconnu",
    /* ---------------- LOGIN ---------------- */
    "login.title": "Connexion",
    "login.email": "Email",
    "login.password": "Mot de passe",
    "login.button": "Se connecter",
    "login.forgotPassword": "Mot de passe oublié ?",
    "login.noAccount": "Pas encore de compte ? S'inscrire",
    "login.incorrectCredentials": "Email ou mot de passe incorrect",
    "login.noRole": "Rôle non défini",
    "login.genericError": "Erreur lors de la connexion",
    "common.loading": "Chargement...",
    "home.artisanAlt": "Artisans qualifiés",
    "home.clientAlt": "Clients satisfaits",
    "home.qualifiedArtisans": "Artisans qualifiés",
    "home.satisfiedClients": "Clients satisfaits",
    /* ---------------- SIGNUP ---------------- */
    "signup.back": "Retour",
    "signup.passwordMismatch": "Les mots de passe ne correspondent pas",
    "signup.signupError": "Erreur lors de l'inscription",
    "signup.alreadyHaveAccount": "Vous avez déjà un compte ?",
    "signup.goToLogin": "Se connecter",
    "signup.acceptTerms": "J'accepte les",
    "signup.termsOfService": "conditions générales d'utilisation",
    "signup.acceptTermsRequired": "Vous devez accepter les conditions générales d'utilisation",
    /* ---------------- CLIENT SIGNUP ---------------- */
    "clientSignup.title": "Inscription Client",
    "clientSignup.firstName": "Prénom",
    "clientSignup.lastName": "NOM",
    "clientSignup.email": "EMAIL",
    "clientSignup.password": "MOT DE PASSE",
    "clientSignup.confirmPassword": "Confirmer mot de passe",
    "clientSignup.city": "VILLE",
    "clientSignup.create": "Créer un compte",
    "clientSignup.creating": "Création en cours...",
    /* ---------------- ARTISAN SIGNUP ---------------- */
    "artisanSignup.title": "Inscription Artisan",
    "artisanSignup.subtitle": "Rejoignez notre réseau d'artisans qualifiés",
    "artisanSignup.client": "Client",
    "artisanSignup.client.desc": "Je cherche un artisan pour mes travaux",
    "artisanSignup.artisan": "Artisan",
    "artisanSignup.artisan.desc": "Je propose mes services aux clients",
    "artisanSignup.selectRole": "Veuillez choisir un rôle avant de continuer.",
    "artisanSignup.fullName": "Nom complet",
    "artisanSignup.email": "EMAIL",
    "artisanSignup.password": "MOT DE PASSE",
    "artisanSignup.confirmPassword": "Confirmer mot de passe",
    "artisanSignup.trade": "Métier",
    "artisanSignup.city": "VILLE",
    "artisanSignup.phone": "Téléphone",
    "artisanSignup.create": "Créer un compte",
    "artisanSignup.creating": "Création en cours...",
    /* ---------------- WORK CATEGORIES ---------------- */
    "work.select": "Sélectionnez un métier",
    "work.plumber": "Plombier",
    "work.electrician": "Électricien",
    "work.carpenter": "Menuisier",
    "work.painter": "Peintre",
    "work.mason": "Maçon",
    "work.roofer": "Couvreur",
    "work.locksmith": "Serrurier",
    "work.heating": "Chauffagiste",
    "work.plasterer": "Plâtrier",
    "work.tiler": "Carreleur",
    "work.toolRental": "Location d'outils",
    "work.babysitting": "Garde d'enfants",
    "work.gardening": "Jardinage",
    "work.shopping": "Courses",
    "work.other": "Autre",
    /* ---------------- PROPOSAL ---------------- */
    "proposal.back": "Retour",
    "proposal.title": "Proposer mes services",
    "proposal.demandDetails": "Détails de la demande",
    "proposal.client": "Client",
    "proposal.department": "Département",
    "proposal.publishedOn": "Publié le",
    "proposal.yourProposal": "Votre proposition",
    "proposal.messageToClient": "Message au client",
    "proposal.messagePlaceholder": "Décrivez votre solution, votre expérience et comment vous pouvez aider ce client...",
    "proposal.proposedPrice": "Prix proposé",
    "proposal.pricePlaceholder": "Ex: 650, 700-800, devis sur place...",
    "proposal.estimatedDuration": "Durée estimée",
    "proposal.durationPlaceholder": "Ex: 2 jours, 1 semaine, selon le devis...",
    "proposal.availability": "Disponibilité",
    "proposal.availabilityPlaceholder": "Quand êtes-vous disponible pour ce travail ?",
    "proposal.important": "Important",
    "proposal.note1": "Le client pourra voir votre proposition et vous contacter directement",
    "proposal.note2": "Vous ne pouvez pas contacter le client directement avant qu'il vous contacte",
    "proposal.note3": "Soyez clair et précis dans votre proposition pour augmenter vos chances",
    "proposal.cancel": "Annuler",
    "proposal.sending": "Envoi en cours...",
    "proposal.sendProposal": "Envoyer la proposition",
    "proposal.loadingDemand": "Chargement de la demande...",
    "proposal.fillRequiredFields": "Veuillez remplir tous les champs obligatoires",
    "proposal.errorCreating": "Erreur lors de la création de la proposition",
    "proposal.demandNotFound": "Demande introuvable",
    "proposal.failedToLoad": "Échec du chargement de la demande",
    "proposal.mustBeLoggedIn": "Vous devez être connecté pour soumettre une proposition",
    "proposal.userIdNotFound": "ID utilisateur introuvable. Veuillez vous reconnecter.",
  },

  en: {
    /* ---------------- HOME PAGE ---------------- */
    "siteTitle": "Coup de Pouce",
    "promoBannerTitle": "Free registration for artisans and clients for 6 months.",
    "promoBannerSubtitle": "Enjoy all features at no cost for a limited time.",
    "qualifiedArtisans": "Qualified Artisans",
    "qualifiedArtisansDesc": "Verified and experienced professionals at your service",
    "artisans": "Artisans",
    "satisfiedClients": "Satisfied Clients",
    "satisfiedClientsDesc": "Thousands of clients trust us",
    "locationNotSpecified": "Location not specified",
    "noOffersAvailable": "No offers available at the moment",
    "welcomeText1": "Welcome to Coup de Pouce, your platform for connecting with qualified artisans.",
    "welcomeText2": "Quickly find the ideal professional for all your renovation, repair, or maintenance work.",
    "welcomeText3": "Our artisans are verified, rated, and ready to meet your needs.",
    "heroTitle": "Coup de Pouce",
    "heroSubtitle": "Find a qualified artisan near you",
    "createAccount": "Create account",
    "login": "Login",
    "footerDescription": "The trusted platform that connects clients with qualified artisans to realize all your projects.",
    "quickLinks": "Quick Links",
    "home": "Home",
    "about": "About",
    "about.title": "About Us",
    "about.subtitle": "Your trusted partner for all your renovation projects",
    "about.mission": "Our Mission",
    "about.mission1": "Connecting clients with qualified and verified artisans",
    "about.mission2": "Facilitating the realization of renovation and repair projects",
    "about.commitment": "We are committed to providing quality service and an exceptional user experience",
    "about.projects": "Projects Completed",
    "about.averageRating": "Average Rating",
    "about.values": "Our Values",
    "about.trust": "Trust",
    "about.trustDesc": "All our artisans are verified and rated",
    "about.efficiency": "Efficiency",
    "about.efficiencyDesc": "Quickly find the ideal artisan for your projects",
    "about.proximity": "Proximity",
    "about.proximityDesc": "Artisans available near you",
    "about.howItWorks": "How It Works",
    "about.signup": "Sign Up",
    "about.signupDesc": "Create your client or artisan account",
    "about.publish": "Publish",
    "about.publishDesc": "Describe your work request",
    "about.select": "Select",
    "about.selectDesc": "Choose from the proposals received",
    "about.realization": "Realization",
    "about.realizationDesc": "Realize your projects with the best artisans",
    "about.ctaTitle": "Ready to start your project?",
    "about.ctaSubtitle": "Join thousands of satisfied clients",
    "about.signUp": "Sign Up",
    "about.contactUs": "Contact Us",
    "about.backHome": "Back to home",
    "signup": "Sign up",
    "services": "Services",
    "clientSpace": "Client space",
    "artisanSpace": "Artisan space",
    "legal": "Legal",
    "terms": "Terms and conditions",
    "privacy": "Privacy policy",
    "artisanTerms": "Artisan terms",
    "contactLink": "Contact",
    "contact.title": "Contact Us",
    "contact.subtitle": "Our team is here to help and answer all your questions",
    "contact.info": "Contact Information",
    "contact.email": "Email",
    "contact.emailValue": "contact@coupdepouce.fr",
    "contact.form": "Contact Form",
    "contact.name": "Name",
    "contact.emailLabel": "Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.userType": "User Type",
    "contact.client": "Client",
    "contact.company": "Company",
    "contact.send": "Send",
    "contact.successTitle": "Message sent successfully!",
    "contact.successMessage": "We will respond to you as soon as possible.",
    "contact.backHome": "Back to home",
    "copyright": "© 2026 Coup de Pouce. All rights reserved.",
    "support": "Support",
    "welcome": "Welcome",
    "error": "Error",
    /* ---------------- CLIENT DASHBOARD ---------------- */
    "clientDashboard.title": "Client Dashboard",
    "dashboard.logout": "Logout",
    "clientDashboard.myDemands": "My Demands",
    "clientDashboard.createDemand": "Create Demand",
    "clientDashboard.proposals": "Proposals",
    "clientDashboard.messages": "Messages",
    "clientDashboard.editProfile": "Edit Profile",
    "clientDashboard.noProposals": "No proposals received.",
    "clientDashboard.contactArtisan": "Contact",
    "clientDashboard.phone": "Phone",
    "clientDashboard.loading": "Loading…",
    "clientDashboard.backToDashboard": "Back to dashboard",
    "clientDashboard.unknownArtisan": "Unknown Artisan",
    "clientDashboard.unspecifiedTrade": "Unspecified Trade",
    "clientDashboard.delete": "Delete",
    "clientDashboard.confirmDelete": "Are you sure you want to delete this proposal?",
    "clientDashboard.confirmDeleteDemand": "Are you sure you want to delete this demand?",
    "clientDashboard.noDemands": "No demands found.",
    "clientDashboard.status": "Status",
    "clientDashboard.createdOn": "Created on",
    "clientDashboard.viewProposals": "View proposals",
    "clientDashboard.client": "Client",
    "clientDashboard.contactClient": "Contact client",
    "clientDashboard.messageCount": "Message count",
    "clientDashboard.openConversation": "Open conversation",
    "clientDashboard.confirmDeleteMessage": "Are you sure you want to delete this conversation?",
    "artisanDashboard.myProposals": "My proposals",
    "artisanDashboard.noProposals": "No proposals sent.",
    "artisanDashboard.myMessages": "My messages",
    "artisanDashboard.noMessages": "No conversations found.",
    "location": "Location",
    "unsubscribe.title": "Unsubscribe",
    "unsubscribe.confirm": "Are you sure you want to unsubscribe?",
    /* ---------------- CREATE DEMAND ---------------- */
    "createDemand.title": "Create Demand",
    "form.title": "Title",
    "form.description": "Description",
    "form.city": "City",
    "form.department": "Department",
    "form.category": "Category",
    "form.budget": "Estimated Budget",
    "form.createDemand": "Create demand",
    "form.categoryPlaceholder": "Ex: Plumbing, Electrical, Carpentry",
    "form.budgetPlaceholder": "Ex: 500-1000€",
    "form.notAuthenticated": "Not authenticated",
    "form.back": "Back",
    /* ---------------- PROFILE EDIT ---------------- */
    "profileEdit.title": "Edit My Profile",
    "profileEdit.loading": "Loading profile...",
    "profileEdit.return": "Return",
    "profileEdit.uploadPhoto": "Upload profile photo",
    "profileEdit.deletePhoto": "Delete photo",
    "profileEdit.fullName": "Full name",
    "profileEdit.email": "Email",
    "profileEdit.phone": "Phone",
    "profileEdit.city": "City",
    "profileEdit.firstName": "First name",
    "profileEdit.lastName": "Last name",
    "profileEdit.trade": "Trade",
    "profileEdit.selectTrade": "Select a trade",
    "profileEdit.description": "Description",
    "profileEdit.experienceYears": "Years of experience",
    "profileEdit.specialties": "Specialties",
    "profileEdit.saving": "Saving...",
    "profileEdit.saveChanges": "Save Changes",
    "profileEdit.profileNotFound": "Profile not found",
    "profileEdit.unableToSave": "Unable to save changes",
    "profileEdit.updatedSuccessfully": "Profile updated successfully",
    /* ---------------- PROPOSALS ---------------- */
    "proposals.title": "Send a proposal",
    "proposals.respondingTo": "You are responding to the demand:",
    "proposals.messageLabel": "Message to send to client",
    "proposals.messagePlaceholder": "Explain how you can help, your availability, etc.",
    "proposals.cancel": "Cancel",
    "proposals.sending": "Sending...",
    "proposals.send": "Send proposal",
    "proposals.loading": "Loading...",
    "proposals.demandNotFound": "Demand not found",
    "proposals.back": "Back",
    /* ---------------- MESSAGES ---------------- */
    "messages.conversation": "Conversation",
    "messages.typeMessage": "Type your message...",
    "messages.send": "Send",
    "messages.downloadFile": "Download file",
    "no_conversations": "No conversations",
    "clickToReply": "Click to reply",
    /* ---------------- HOME SLIDESHOW ---------------- */
    "slideshow.title": "Latest Demands",
    "slideshow.noProposals": "No proposals available",
    /* ---------------- ARTISAN DASHBOARD ---------------- */
    "artisanHeader": "Artisan dashboard",
    "logout": "Logout",
    "proposals": "Proposals",
    "messages": "Messages",
    "editProfile": "Edit Profile",
    "unsubscribe": "Unsubscribe",
    "unsubscribeConfirm": "Are you sure you want to unsubscribe?",
    /* ---------------- ARTISAN PROFILE ---------------- */
    "artisanProfileTitle": "My Artisan Profile",
    "artisanProfile": "My Artisan Profile",
    "backToDashboard": "Back to dashboard",
    "loading": "Loading...",
    "profileUpdated": "Profile updated successfully",
    "errorLoadingProfile": "Error loading profile",
    "errorUpdatingProfile": "Error updating profile",
    "connectionError": "Connection error",
    "fullName": "Full name",
    "email": "Email",
    "phone": "Phone",
    "city": "City",
    "trade": "Trade/Profession",
    "yearsOfExperience": "Years of experience",
    "description": "Description",
    "specialties": "Specialties",
    "descriptionPlaceholder": "Describe your services and expertise...",
    "specialtiesPlaceholder": "Ex: Plumbing, Heating, Bathroom",
    "saveChanges": "Save changes",
    "saving": "Saving...",
    /* ---------------- ARTISAN DASHBOARD INSCRIPTION INFO ---------------- */
    "myArtisanProfile": "My Artisan Profile",
    "descriptionSection": "Description",
    "descriptionPlaceholder2": "Describe your activity...",
    "experienceYears": "Years of experience",
    "specialtiesSection": "Specialties",
    "specialtiesPlaceholder2": "Ex: Masonry, Renovation...",
    "contact": "Contact",
    "phonePlaceholder": "Phone",
    "cityPlaceholder": "City",
    "cancel": "Cancel",
    "save": "Save",
    "updateError": "Error during update",
    /* ---------------- ARTISAN CONTACTS ---------------- */
    "welcomeContacts": "Welcome, {name} - My contacts",
    "manageContacts": "Manage your communications with clients",
    "loadingContacts": "Loading contacts...",
    "noContacts": "No contacts",
    "noContactsDesc": "You don't have any contacts with clients yet.",
    "viewRequests": "View available requests",
    "deleteContact": "Delete",
    "deleteContactConfirm": "Are you sure you want to delete this contact?",
    "contactDetails": "Contact details",
    "clientInfo": "Client information",
    "name": "Name",
    "status": "Status",
    "address": "Address",
    "demandInfo": "Demand information",
    "title": "Title",
    "category": "Category",
    "contactDate": "Contact date",
    "proposedPrice": "Proposed price",
    "communication": "Communication",
    "client": "Client",
    "yourResponse": "Your response",
    "responseSent": "Response sent",
    "close": "Close",
    "contactClient": "Contact client",
    "statusInitial": "Initial",
    "statusOngoing": "Ongoing",
    "statusCompleted": "Completed",
    "statusUnknown": "Unknown",
    /* ---------------- SIGNUP ---------------- */
    "signup.back": "Back",
    "signup.passwordMismatch": "Passwords do not match",
    "signup.signupError": "Error during signup",
    "signup.alreadyHaveAccount": "Already have an account?",
    "signup.goToLogin": "Login",
    "signup.acceptTerms": "I accept the",
    "signup.termsOfService": "terms of service",
    "signup.acceptTermsRequired": "You must accept the terms of service",
    "signup.client": "Client",
    "signup.client.desc": "I'm looking for an artisan for my work",
    "signup.artisan": "Artisan",
    "signup.artisan.desc": "I offer my services to clients",
    "signup.selectRole": "Please select a role before continuing.",
    /* ---------------- CLIENT SIGNUP ---------------- */
    "clientSignup.title": "Client Sign Up",
    "clientSignup.firstName": "First Name",
    "clientSignup.lastName": "Last Name",
    "clientSignup.email": "Email",
    "clientSignup.password": "Password",
    "clientSignup.confirmPassword": "Confirm Password",
    "clientSignup.city": "City",
    "clientSignup.create": "Create Account",
    "clientSignup.creating": "Creating...",
    /* ---------------- ARTISAN SIGNUP ---------------- */
    "artisanSignup.title": "Artisan Sign Up",
    "artisanSignup.subtitle": "Join our network of qualified artisans",
    "artisanSignup.fullName": "Full Name",
    "artisanSignup.email": "Email",
    "artisanSignup.password": "Password",
    "artisanSignup.confirmPassword": "Confirm Password",
    "artisanSignup.trade": "Trade",
    "artisanSignup.city": "City",
    "artisanSignup.phone": "Phone",
    "artisanSignup.create": "Create Account",
    "artisanSignup.creating": "Creating...",
    /* ---------------- WORK CATEGORIES ---------------- */
    "work.select": "Select a trade",
    "work.plumber": "Plumber",
    "work.electrician": "Electrician",
    "work.carpenter": "Carpenter",
    "work.painter": "Painter",
    "work.mason": "Mason",
    "work.roofer": "Roofer",
    "work.locksmith": "Locksmith",
    "work.heating": "Heating Technician",
    "work.plasterer": "Plasterer",
    "work.tiler": "Tiler",
    "work.toolRental": "Tool Rental",
    "work.babysitting": "Babysitting",
    "work.gardening": "Gardening",
    "work.shopping": "Shopping",
    "work.other": "Other",
    /* ---------------- PROPOSAL ---------------- */
    "proposal.back": "Back",
    "proposal.title": "Offer my services",
    "proposal.demandDetails": "Demand details",
    "proposal.client": "Client",
    "proposal.department": "Department",
    "proposal.publishedOn": "Published on",
    "proposal.yourProposal": "Your proposal",
    "proposal.messageToClient": "Message to client",
    "proposal.messagePlaceholder": "Describe your solution, your experience, and how you can help this client...",
    "proposal.proposedPrice": "Proposed price",
    "proposal.pricePlaceholder": "Ex: 650, 700-800, on-site quote...",
    "proposal.estimatedDuration": "Estimated duration",
    "proposal.durationPlaceholder": "Ex: 2 days, 1 week, depending on quote...",
    "proposal.availability": "Availability",
    "proposal.availabilityPlaceholder": "When are you available for this work?",
    "proposal.important": "Important",
    "proposal.note1": "The client will be able to see your proposal and contact you directly",
    "proposal.note2": "You cannot contact the client directly before they contact you",
    "proposal.note3": "Be clear and precise in your proposal to increase your chances",
    "proposal.cancel": "Cancel",
    "proposal.sending": "Sending...",
    "proposal.sendProposal": "Send proposal",
    "proposal.loadingDemand": "Loading demand...",
    "proposal.fillRequiredFields": "Please fill in all required fields",
    "proposal.errorCreating": "Error creating proposal",
    "proposal.demandNotFound": "Demand not found",
    "proposal.failedToLoad": "Failed to load demand",
    "proposal.mustBeLoggedIn": "You must be logged in to submit a proposal",
    "proposal.userIdNotFound": "User ID not found. Please try logging in again.",
  }
}

/* -------------------------------------------------------
   PROVIDER
------------------------------------------------------- */
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const saved = localStorage.getItem('language') as Language
    if (saved === 'fr' || saved === 'en') setLanguage(saved)
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (mounted) localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

/* -------------------------------------------------------
   HOOK
------------------------------------------------------- */
export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider')
  return ctx
}
