'use client'

import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode
} from 'react'

type Language = 'fr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

/* -------------------------------------------------------
   TRANSLATIONS
------------------------------------------------------- */
const translations: Record<Language, Record<string, string>> = {
  fr: {
    /* ---------------- HOME PAGE ---------------- */
    "siteTitle": "Coup de Pouce",
    "promoBannerTitle": "Inscription gratuite pour artisans et clients pendant 6 mois.",
    "promoBannerSubtitle": "Profitez de toutes les fonctionnalités sans frais pendant une période limitée.",
    "qualifiedArtisans": "Artisans qualifiés",
    "qualifiedArtisansDesc": "Des professionnels vérifiés et expérimentés à votre service",
    "satisfiedClients": "Clients satisfaits",
    "satisfiedClientsDesc": "Des milliers de clients nous font confiance",
    "welcomeText1": "Bienvenue sur Coup de Pouce, votre plateforme de mise en relation avec des artisans qualifiés.",
    "welcomeText2": "Trouvez rapidement le professionnel idéal pour tous vos travaux de rénovation, de réparation ou d'entretien.",
    "welcomeText3": "Nos artisans sont vérifiés, notés et prêts à répondre à vos besoins.",
    "heroTitle": "Coup de Pouce",
    "heroSubtitle": "Trouvez un artisan qualifié près de chez vous",
    "createAccount": "Créer un compte",
    "login": "Se connecter",
    "footerDescription": "La plateforme de confiance qui met en relation les clients avec des artisans qualifiés pour réaliser tous vos projets.",
    "quickLinks": "Liens rapides",
    "home": "Accueil",
    "about": "À propos",
    "signup": "S'inscrire",
    "services": "Services",
    "clientSpace": "Espace client",
    "artisanSpace": "Espace artisan",
    "legal": "Légal",
    "terms": "Conditions générales",
    "privacy": "Politique de confidentialité",
    "artisanTerms": "Conditions artisans",
    "contactLink": "Contact",
    "copyright": "© 2026 Coup de Pouce. Tous droits réservés.",
    "support": "Support",
    "welcome": "Bienvenue",
    "error": "Erreur",
    /* ---------------- CLIENT DASHBOARD ---------------- */
    "clientDashboard.title": "Tableau de bord client",
    "dashboard.logout": "Déconnexion",
    "clientDashboard.myDemands": "Mes demandes",
    "clientDashboard.createDemand": "Créer une demande",
    "clientDashboard.proposals": "Propositions",
    "clientDashboard.messages": "Messages",
    "clientDashboard.editProfile": "Modifier le profil",
    "unsubscribe.title": "Se désinscrire",
    "unsubscribe.confirm": "Êtes-vous sûr de vouloir vous désinscrire ?",
    /* ---------------- CREATE DEMAND ---------------- */
    "createDemand.title": "Créer une demande",
    "form.title": "Titre",
    "form.description": "Description",
    "form.city": "Ville",
    "form.department": "Département",
    "form.createDemand": "Créer la demande",
    "form.notAuthenticated": "Non authentifié",
    "form.back": "Retour",
    /* ---------------- PROFILE EDIT ---------------- */
    "profileEdit.title": "Modifier mon profil",
    "profileEdit.loading": "Chargement du profil...",
    "profileEdit.return": "Retour",
    "profileEdit.uploadPhoto": "Uploader une photo de profil",
    "profileEdit.deletePhoto": "Supprimer la photo",
    "profileEdit.fullName": "Nom complet",
    "profileEdit.email": "Email",
    "profileEdit.phone": "Téléphone",
    "profileEdit.city": "Ville",
    "profileEdit.firstName": "Prénom",
    "profileEdit.lastName": "Nom",
    "profileEdit.trade": "Métier",
    "profileEdit.selectTrade": "Sélectionnez un métier",
    "profileEdit.description": "Description",
    "profileEdit.experienceYears": "Années d'expérience",
    "profileEdit.specialties": "Spécialités",
    "profileEdit.saving": "Enregistrement...",
    "profileEdit.saveChanges": "Enregistrer les modifications",
    "profileEdit.profileNotFound": "Profil introuvable",
    "profileEdit.unableToSave": "Impossible d'enregistrer les modifications",
    "profileEdit.updatedSuccessfully": "Profil mis à jour avec succès",
    /* ---------------- PROPOSALS ---------------- */
    "proposals.title": "Envoyer une proposition",
    "proposals.respondingTo": "Vous répondez à la demande :",
    "proposals.messageLabel": "Message à envoyer au client",
    "proposals.messagePlaceholder": "Expliquez comment vous pouvez aider, vos disponibilités, etc.",
    "proposals.cancel": "Annuler",
    "proposals.sending": "Envoi en cours...",
    "proposals.send": "Envoyer la proposition",
    "proposals.loading": "Chargement...",
    "proposals.demandNotFound": "Demande introuvable",
    "proposals.back": "Retour",
    /* ---------------- MESSAGES ---------------- */
    "messages.conversation": "Conversation",
    "messages.typeMessage": "Tapez votre message...",
    "messages.send": "Envoyer",
    "messages.downloadFile": "Télécharger le fichier",
    "no_conversations": "Aucune conversation",
    /* ---------------- HOME SLIDESHOW ---------------- */
    "slideshow.title": "Dernières demandes",
    "slideshow.noProposals": "Aucune proposition disponible",
    /* ---------------- ARTISAN DASHBOARD ---------------- */
    "artisanHeader": "Tableau de bord artisan",
    "logout": "Se déconnecter",
    "proposals": "Propositions",
    "messages": "Messages",
    "editProfile": "Modifier le profil",
    "unsubscribe": "Se désinscrire",
    "unsubscribeConfirm": "Êtes-vous sûr de vouloir vous désinscrire ?",
    /* ---------------- ARTISAN PROFILE ---------------- */
    "artisanProfile": "Mon profil artisan",
    "backToDashboard": "Retour au tableau de bord",
    "loading": "Chargement...",
    "profileUpdated": "Profil mis à jour avec succès",
    "errorLoadingProfile": "Erreur lors du chargement du profil",
    "errorUpdatingProfile": "Erreur lors de la mise à jour du profil",
    "connectionError": "Erreur de connexion",
    "fullName": "Nom complet",
    "email": "Email",
    "phone": "Téléphone",
    "city": "Ville",
    "trade": "Métier",
    "yearsOfExperience": "Années d'expérience",
    "description": "Description",
    "specialties": "Spécialités",
    "descriptionPlaceholder": "Décrivez vos services et votre expertise...",
    "specialtiesPlaceholder": "Ex: Plomberie, Chauffage, Salle de bain",
    "saveChanges": "Enregistrer les modifications",
    "saving": "Enregistrement...",
    /* ---------------- ARTISAN DASHBOARD INSCRIPTION INFO ---------------- */
    "myArtisanProfile": "Mon Profil Artisan",
    "descriptionSection": "Description",
    "descriptionPlaceholder2": "Décrivez votre activité...",
    "experienceYears": "Années d'expérience",
    "specialtiesSection": "Spécialités",
    "specialtiesPlaceholder2": "Ex: Maçonnerie, Rénovation...",
    "contact": "Contact",
    "phonePlaceholder": "Téléphone",
    "cityPlaceholder": "Ville",
    "cancel": "Annuler",
    "save": "Enregistrer",
    "updateError": "Erreur lors de la mise à jour",
    /* ---------------- ARTISAN CONTACTS ---------------- */
    "welcomeContacts": "Bienvenue, {name} - Mes contacts",
    "manageContacts": "Gérez vos communications avec les clients",
    "loadingContacts": "Chargement des contacts...",
    "noContacts": "Aucun contact",
    "noContactsDesc": "Vous n'avez pas encore de contacts avec des clients.",
    "viewRequests": "Consulter les demandes disponibles",
    "deleteContact": "Supprimer",
    "deleteContactConfirm": "Êtes-vous sûr de vouloir supprimer ce contact ?",
    "contactDetails": "Détails du contact",
    "clientInfo": "Informations client",
    "name": "Nom",
    "status": "Statut",
    "address": "Adresse",
    "demandInfo": "Informations sur la demande",
    "title": "Titre",
    "category": "Catégorie",
    "contactDate": "Date du contact",
    "proposedPrice": "Prix proposé",
    "communication": "Communication",
    "client": "Client",
    "yourResponse": "Votre réponse",
    "responseSent": "Réponse envoyée",
    "close": "Fermer",
    "contactClient": "Contacter le client",
    "statusInitial": "Initial",
    "statusOngoing": "En cours",
    "statusCompleted": "Terminé",
    "statusUnknown": "Inconnu",
    /* ---------------- LOGIN ---------------- */
    "login.title": "Connexion",
    "login.email": "Email",
    "login.password": "Mot de passe",
    "login.button": "Se connecter",
    "login.forgotPassword": "Mot de passe oublié ?",
    "login.noAccount": "Pas encore de compte ? S'inscrire",
    "login.incorrectCredentials": "Email ou mot de passe incorrect",
    "login.noRole": "Rôle non défini",
    "login.genericError": "Erreur lors de la connexion",
    "common.loading": "Chargement...",
    "home.artisanAlt": "Artisans qualifiés",
    "home.clientAlt": "Clients satisfaits",
    "home.qualifiedArtisans": "Artisans qualifiés",
    "home.satisfiedClients": "Clients satisfaits",
    /* ---------------- SIGNUP ---------------- */
    "signup.back": "Retour",
    "signup.passwordMismatch": "Les mots de passe ne correspondent pas",
    "signup.signupError": "Erreur lors de l'inscription",
    "signup.alreadyHaveAccount": "Vous avez déjà un compte ?",
    "signup.goToLogin": "Se connecter",
    /* ---------------- CLIENT SIGNUP ---------------- */
    "clientSignup.title": "Inscription Client",
    "clientSignup.firstName": "Prénom",
    "clientSignup.lastName": "NOM",
    "clientSignup.email": "EMAIL",
    "clientSignup.password": "MOT DE PASSE",
    "clientSignup.confirmPassword": "Confirmer mot de passe",
    "clientSignup.city": "VILLE",
    "clientSignup.create": "Créer un compte",
    "clientSignup.creating": "Création en cours...",
    /* ---------------- ARTISAN SIGNUP ---------------- */
    "artisanSignup.title": "Inscription Artisan",
    "artisanSignup.subtitle": "Rejoignez notre réseau d'artisans qualifiés",
    "artisanSignup.fullName": "Nom complet",
    "artisanSignup.email": "EMAIL",
    "artisanSignup.password": "MOT DE PASSE",
    "artisanSignup.confirmPassword": "Confirmer mot de passe",
    "artisanSignup.trade": "Métier",
    "artisanSignup.city": "VILLE",
    "artisanSignup.phone": "Téléphone",
    "artisanSignup.create": "Créer un compte",
    "artisanSignup.creating": "Création en cours...",
    /* ---------------- WORK CATEGORIES ---------------- */
    "work.select": "Sélectionnez un métier",
    "work.plumber": "Plombier",
    "work.electrician": "Électricien",
    "work.carpenter": "Menuisier",
    "work.painter": "Peintre",
    "work.mason": "Maçon",
    "work.roofer": "Couvreur",
    "work.locksmith": "Serrurier",
    "work.heating": "Chauffagiste",
    "work.plasterer": "Plâtrier",
    "work.tiler": "Carreleur",
    "work.toolRental": "Location d'outils",
    "work.babysitting": "Garde d'enfants",
    "work.gardening": "Jardinage",
    "work.shopping": "Courses",
    "work.other": "Autre"
  },

  en: {
    /* ---------------- HOME PAGE ---------------- */
    "siteTitle": "Coup de Pouce",
    "promoBannerTitle": "Free registration for artisans and clients for 6 months.",
    "promoBannerSubtitle": "Enjoy all features at no cost for a limited time.",
    "qualifiedArtisans": "Qualified Artisans",
    "qualifiedArtisansDesc": "Verified and experienced professionals at your service",
    "satisfiedClients": "Satisfied Clients",
    "satisfiedClientsDesc": "Thousands of clients trust us",
    "welcomeText1": "Welcome to Coup de Pouce, your platform for connecting with qualified artisans.",
    "welcomeText2": "Quickly find the ideal professional for all your renovation, repair, or maintenance work.",
    "welcomeText3": "Our artisans are verified, rated, and ready to meet your needs.",
    "heroTitle": "Coup de Pouce",
    "heroSubtitle": "Find a qualified artisan near you",
    "createAccount": "Create account",
    "login": "Login",
    "footerDescription": "The trusted platform that connects clients with qualified artisans to realize all your projects.",
    "quickLinks": "Quick Links",
    "home": "Home",
    "about": "About",
    "signup": "Sign up",
    "services": "Services",
    "clientSpace": "Client space",
    "artisanSpace": "Artisan space",
    "legal": "Legal",
    "terms": "Terms and conditions",
    "privacy": "Privacy policy",
    "artisanTerms": "Artisan terms",
    "contactLink": "Contact",
    "copyright": "© 2026 Coup de Pouce. All rights reserved.",
    "support": "Support",
    "welcome": "Welcome",
    "error": "Error",
    /* ---------------- CLIENT DASHBOARD ---------------- */
    "clientDashboard.title": "Client Dashboard",
    "dashboard.logout": "Logout",
    "clientDashboard.myDemands": "My Demands",
    "clientDashboard.createDemand": "Create Demand",
    "clientDashboard.proposals": "Proposals",
    "clientDashboard.messages": "Messages",
    "clientDashboard.editProfile": "Edit Profile",
    "unsubscribe.title": "Unsubscribe",
    "unsubscribe.confirm": "Are you sure you want to unsubscribe?",
    /* ---------------- CREATE DEMAND ---------------- */
    "createDemand.title": "Create Demand",
    "form.title": "Title",
    "form.description": "Description",
    "form.city": "City",
    "form.department": "Department",
    "form.createDemand": "Create demand",
    "form.notAuthenticated": "Not authenticated",
    "form.back": "Back",
    /* ---------------- PROFILE EDIT ---------------- */
    "profileEdit.title": "Edit My Profile",
    "profileEdit.loading": "Loading profile...",
    "profileEdit.return": "Return",
    "profileEdit.uploadPhoto": "Upload profile photo",
    "profileEdit.deletePhoto": "Delete photo",
    "profileEdit.fullName": "Full name",
    "profileEdit.email": "Email",
    "profileEdit.phone": "Phone",
    "profileEdit.city": "City",
    "profileEdit.firstName": "First name",
    "profileEdit.lastName": "Last name",
    "profileEdit.trade": "Trade",
    "profileEdit.selectTrade": "Select a trade",
    "profileEdit.description": "Description",
    "profileEdit.experienceYears": "Years of experience",
    "profileEdit.specialties": "Specialties",
    "profileEdit.saving": "Saving...",
    "profileEdit.saveChanges": "Save Changes",
    "profileEdit.profileNotFound": "Profile not found",
    "profileEdit.unableToSave": "Unable to save changes",
    "profileEdit.updatedSuccessfully": "Profile updated successfully",
    /* ---------------- PROPOSALS ---------------- */
    "proposals.title": "Send a proposal",
    "proposals.respondingTo": "You are responding to the demand:",
    "proposals.messageLabel": "Message to send to client",
    "proposals.messagePlaceholder": "Explain how you can help, your availability, etc.",
    "proposals.cancel": "Cancel",
    "proposals.sending": "Sending...",
    "proposals.send": "Send proposal",
    "proposals.loading": "Loading...",
    "proposals.demandNotFound": "Demand not found",
    "proposals.back": "Back",
    /* ---------------- MESSAGES ---------------- */
    "messages.conversation": "Conversation",
    "messages.typeMessage": "Type your message...",
    "messages.send": "Send",
    "messages.downloadFile": "Download file",
    "no_conversations": "No conversations",
    /* ---------------- HOME SLIDESHOW ---------------- */
    "slideshow.title": "Latest Demands",
    "slideshow.noProposals": "No proposals available",
    /* ---------------- ARTISAN DASHBOARD ---------------- */
    "artisanHeader": "Artisan dashboard",
    "logout": "Logout",
    "proposals": "Proposals",
    "messages": "Messages",
    "editProfile": "Edit Profile",
    "unsubscribe": "Unsubscribe",
    "unsubscribeConfirm": "Are you sure you want to unsubscribe?",
    /* ---------------- ARTISAN PROFILE ---------------- */
    "artisanProfile": "My Artisan Profile",
    "backToDashboard": "Back to dashboard",
    "loading": "Loading...",
    "profileUpdated": "Profile updated successfully",
    "errorLoadingProfile": "Error loading profile",
    "errorUpdatingProfile": "Error updating profile",
    "connectionError": "Connection error",
    "fullName": "Full name",
    "email": "Email",
    "phone": "Phone",
    "city": "City",
    "trade": "Trade/Profession",
    "yearsOfExperience": "Years of experience",
    "description": "Description",
    "specialties": "Specialties",
    "descriptionPlaceholder": "Describe your services and expertise...",
    "specialtiesPlaceholder": "Ex: Plumbing, Heating, Bathroom",
    "saveChanges": "Save changes",
    "saving": "Saving...",
    /* ---------------- ARTISAN DASHBOARD INSCRIPTION INFO ---------------- */
    "myArtisanProfile": "My Artisan Profile",
    "descriptionSection": "Description",
    "descriptionPlaceholder2": "Describe your activity...",
    "experienceYears": "Years of experience",
    "specialtiesSection": "Specialties",
    "specialtiesPlaceholder2": "Ex: Masonry, Renovation...",
    "contact": "Contact",
    "phonePlaceholder": "Phone",
    "cityPlaceholder": "City",
    "cancel": "Cancel",
    "save": "Save",
    "updateError": "Error during update",
    /* ---------------- ARTISAN CONTACTS ---------------- */
    "welcomeContacts": "Welcome, {name} - My contacts",
    "manageContacts": "Manage your communications with clients",
    "loadingContacts": "Loading contacts...",
    "noContacts": "No contacts",
    "noContactsDesc": "You don't have any contacts with clients yet.",
    "viewRequests": "View available requests",
    "deleteContact": "Delete",
    "deleteContactConfirm": "Are you sure you want to delete this contact?",
    "contactDetails": "Contact details",
    "clientInfo": "Client information",
    "name": "Name",
    "status": "Status",
    "address": "Address",
    "demandInfo": "Demand information",
    "title": "Title",
    "category": "Category",
    "contactDate": "Contact date",
    "proposedPrice": "Proposed price",
    "communication": "Communication",
    "client": "Client",
    "yourResponse": "Your response",
    "responseSent": "Response sent",
    "close": "Close",
    "contactClient": "Contact client",
    "statusInitial": "Initial",
    "statusOngoing": "Ongoing",
    "statusCompleted": "Completed",
    "statusUnknown": "Unknown",
    /* ---------------- SIGNUP ---------------- */
    "signup.back": "Back",
    "signup.passwordMismatch": "Passwords do not match",
    "signup.signupError": "Error during signup",
    "signup.alreadyHaveAccount": "Already have an account?",
    "signup.goToLogin": "Login",
    /* ---------------- CLIENT SIGNUP ---------------- */
    "clientSignup.title": "Client Sign Up",
    "clientSignup.firstName": "First Name",
    "clientSignup.lastName": "Last Name",
    "clientSignup.email": "Email",
    "clientSignup.password": "Password",
    "clientSignup.confirmPassword": "Confirm Password",
    "clientSignup.city": "City",
    "clientSignup.create": "Create Account",
    "clientSignup.creating": "Creating...",
    /* ---------------- ARTISAN SIGNUP ---------------- */
    "artisanSignup.title": "Artisan Sign Up",
    "artisanSignup.subtitle": "Join our network of qualified artisans",
    "artisanSignup.fullName": "Full Name",
    "artisanSignup.email": "Email",
    "artisanSignup.password": "Password",
    "artisanSignup.confirmPassword": "Confirm Password",
    "artisanSignup.trade": "Trade",
    "artisanSignup.city": "City",
    "artisanSignup.phone": "Phone",
    "artisanSignup.create": "Create Account",
    "artisanSignup.creating": "Creating...",
    /* ---------------- WORK CATEGORIES ---------------- */
    "work.select": "Select a trade",
    "work.plumber": "Plumber",
    "work.electrician": "Electrician",
    "work.carpenter": "Carpenter",
    "work.painter": "Painter",
    "work.mason": "Mason",
    "work.roofer": "Roofer",
    "work.locksmith": "Locksmith",
    "work.heating": "Heating Technician",
    "work.plasterer": "Plasterer",
    "work.tiler": "Tiler",
    "work.toolRental": "Tool Rental",
    "work.babysitting": "Babysitting",
    "work.gardening": "Gardening",
    "work.shopping": "Shopping",
    "work.other": "Other"
  }
}

/* -------------------------------------------------------
   PROVIDER
------------------------------------------------------- */
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const saved = localStorage.getItem('language') as Language
    if (saved === 'fr' || saved === 'en') setLanguage(saved)
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (mounted) localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

/* -------------------------------------------------------
   HOOK
------------------------------------------------------- */
export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider')
  return ctx
}
